# Generated by Django 2.2.1 on 2019-05-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter',
            field=models.TextField(default=''),
        ),
    ]
